---
title: "Plotting Echo-Chamber ABM"
author: "Peter Thramkrongart and Asger Lakkenborg"
date: "11/5/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Here we are loading the data
```{r Loading data}

setwd("D:\\Users\\thram_000\\OneDrive\\cog data\\SocKult\\ABM_SocKult")
pacman::p_load(rJava, RNetLogo, tidyverse, parallel,egg,wesanderson)

ABM_Data <- read_csv("D:\\Users\\thram_000\\OneDrive\\cog data\\SocKult\\ABM_SocKult\\ABM_Data10.csv")

distributionData <- read_csv("DistributionData10.csv")



ABM_Data <-
  ABM_Data %>% mutate_at(
    c(
      "censorship_mod",
      "numlearners",
      "broadcast_freq",
      "prune_sd_mod",
      "search_distance",
      "run_id",
      "param_set_id"
    ),
    as.factor
  )

distributionData <-
  distributionData %>% mutate_at(
    c(
      "censorship_mod",
      "numlearners",
      "broadcast_freq",
      "prune_sd_mod",
      "search_distance",
      "run_id",
      "param_set_id"
    ),
    as.factor
  ) 

ABM_Data <- ABM_Data %>% 
  rename(
    Number_of_agents = numlearners,
    Broadcast_frequency = broadcast_freq,
    Censorship_sd_mod = censorship_mod,
    Search_distance = search_distance
    )


distributionData <- distributionData %>% 
  rename(
    Number_of_agents = numlearners,
    Broadcast_frequency = broadcast_freq,
    Censorship_sd_mod = censorship_mod,
    Search_distance = search_distance
    )

ABM_DataBasic <- ABM_Data %>% 
  filter(Number_of_agents == 1000,Broadcast_frequency == "None", Censorship_sd_mod == "None")

distributionDataBasic <- distributionData %>% 
  filter(Number_of_agents == 1000,Broadcast_frequency == "None", Censorship_sd_mod == "None")

theme_set(theme_bw(base_size = 20) + theme(legend.position = "bottom"))

```


```{r,fig.width = 15,fig.height= 12}

distributionData %>% filter(Number_of_agents == 1000) %>%
  ggplot(aes(`prior-val`,
             Search_distance,
             fill = prune_sd_mod))  +
  facet_wrap(Censorship_sd_mod ~ Broadcast_frequency, labeller = label_both) + geom_boxplot(outlier.size = 0.1) +
  ggtitle("Distribution of beliefs") +
  labs(x = "Belief state")


```




```{r,fig.width = 15,fig.height= 12}
ABM_Data %>% filter(Number_of_agents == 1000, Search_distance != 10) %>%
  ggplot(aes(step_id,
             glob_p_h,
             color = prune_sd_mod)) +
  facet_wrap(Search_distance ~ Censorship_sd_mod ~ Broadcast_frequency,
             labeller = label_both) +
  geom_smooth(size = 0.1, alpha = 0.1) +
  ggtitle("Growth of confidence over time") +
  labs(y = "Confidence, P(H|E)")

```

```{r,fig.width = 15,fig.height= 12}
ABM_Data %>%
  filter(Number_of_agents == 1000) %>%
  ggplot(aes(step_id,
             glob_p_h,
             linetype = Censorship_sd_mod,
             color = prune_sd_mod)) +
  facet_wrap(Search_distance  ~ Broadcast_frequency, labeller = label_both) +
  geom_smooth(size = 0.1, alpha = 0.1) +
  ggtitle("Growth of confidence over time") +
  labs(y = "Confidence, P(H|E)")

```

```{r,fig.width = 15,fig.height= 12}
ABM_Data %>%
  ggplot(aes(step_id,
             glob_p_h,
             linetype = Censorship_sd_mod,
             color = prune_sd_mod)) +
  facet_wrap(Search_distance ~ Number_of_agents ~ Broadcast_frequency,
             labeller = label_both) +
  geom_smooth(size = 0.1, alpha = 0.1) +
  ggtitle("Growth of confidence over time") +
  labs(y = "Confidence, P(H|E)")

```

```{r, fig.width = 15,fig.height= 12}
ABM_Data %>%
  filter(Number_of_agents == 1000) %>%
  ggplot(aes(step_id,
             glob_purity,
             linetype = Censorship_sd_mod,
             color = prune_sd_mod,)) +
  facet_wrap(Search_distance  ~ Broadcast_frequency, labeller = label_both) +
  geom_smooth(size = 0.1, alpha = 0.1) +
  ggtitle("Growth of belief purity over time") +
  labs(y = "Belief Purity")



```

```{r,fig.width = 15,fig.height= 12}
distributionData %>% filter(step_id == 50,
                            Number_of_agents == 1000,
                            Censorship_sd_mod == "None") %>%
  ggplot(aes(`prior-val`,
             color = prune_sd_mod)) +
  geom_density() +
  facet_wrap(Search_distance ~
               Broadcast_frequency, labeller = label_both) +
  ggtitle("Distribution of beliefs")  +
  labs(x = "Belief state")



```

```{r,fig.width = 15,fig.height= 12}

distributionData %>%
  filter(step_id == "1", Number_of_agents == 1000) %>%
  ggplot(aes(`prior-val`,
             color = prune_sd_mod,
             linetype = Censorship_sd_mod)) +
  facet_wrap(Broadcast_frequency ~ run_id, labeller = label_both) +
  geom_density() + ggtitle("Distribution of beliefs") +
  labs(x = "Belief state")


```

```{r,fig.width = 15,fig.height= 12}

distributionData %>%
  filter(Number_of_agents == 1000, Search_distance == 10, step_id == 50) %>%
  ggplot(aes(`prior-val`,
             color = prune_sd_mod)) +
  facet_wrap(Broadcast_frequency~Censorship_sd_mod, labeller = label_both) +
  geom_density() +
  ggtitle("Distribution of beliefs") +
  labs(x = "Belief state")


```

```{r,fig.width = 15,fig.height= 12}

ABM_Data %>%
  filter(Number_of_agents == 1000, Search_distance == 10) %>%
  ggplot(aes(step_id,
             glob_sd,
             color = Censorship_sd_mod,
             linetype = Censorship_sd_mod)) +
  facet_wrap(Broadcast_frequency ~ prune_sd_mod, labeller = label_both) +
  geom_smooth(alpha = 0.1) +
  ggtitle("Decrease in SD of belief over time") +
  labs(y = "SD of Beliefs")

```

```{r}

ABM_DataShort <- read_csv("D:\\Users\\thram_000\\OneDrive\\cog data\\SocKult\\ABM_SocKult\\ABM_DataShort5.csv")

distributionDataShort <- read_csv("distributionDataShort5.csv")

ABM_DataShort <-
  ABM_DataShort %>% mutate_at(
    c(
      "censorship_mod",
      "numlearners",
      "broadcast_freq",
      "prune_sd_mod",
      "search_distance",
      "run_id",
      "param_set_id"
    ),
    as.factor
  )

distributionDataShort <-
  distributionDataShort %>% mutate_at(
    c(
      "censorship_mod",
      "numlearners",
      "broadcast_freq",
      "prune_sd_mod",
      "search_distance",
      "run_id",
      "param_set_id"
    ),
    as.factor
  ) 


ABM_DataShort <- ABM_DataShort %>%
  rename(
    Number_of_agents = numlearners,
    Broadcast_frequency = broadcast_freq,
    Censorship_sd_mod = censorship_mod,
    Search_distance = search_distance
  )


distributionDataShort <- distributionDataShort %>%
  rename(
    Number_of_agents = numlearners,
    Broadcast_frequency = broadcast_freq,
    Censorship_sd_mod = censorship_mod,
    Search_distance = search_distance
  )

```

```{r,fig.width = 15,fig.height= 12}

distributionDataShort %>%
  filter(Search_distance == 10, step_id == 50) %>%
  ggplot(aes(`prior-val`,
             color = Censorship_sd_mod)) +
  facet_wrap(Broadcast_frequency ~ prune_sd_mod, labeller = label_both) +
  geom_density() +
  ggtitle("Distribution of beliefs") +
  labs(x = "Belief state") +
  scale_color_manual(values = wes_palette("FantasticFox1"))




```

```{r, fig.width = 15,fig.height= 12}
ABM_DataShort %>%
  ggplot(aes(step_id,
             glob_purity,
             color = prune_sd_mod,
             linetype = Search_distance)) +
  facet_wrap( .~ Broadcast_frequency, labeller = label_both) +
  geom_smooth(size = 0.1, alpha = 0.1) +
  ggtitle("Growth of belief purity over time") +
  labs(y = "Belief Purity") +
  scale_color_manual(values = wes_palette("FantasticFox1"))

```

```{r,fig.width = 15,fig.height= 12}
ABM_DataShort %>%
  filter(Number_of_agents == 1000) %>%
  ggplot(aes(step_id,
             glob_p_h,
             color = Censorship_sd_mod,
             linetype = Search_distance)) +
  facet_wrap(~Broadcast_frequency,
             labeller = label_both) + geom_smooth(size = 0.1, alpha = 0.1) +
  ggtitle("Growth of confidence over time") +
  labs(y = "Confidence, P(H|E)") +
  scale_color_manual(values = wes_palette("FantasticFox1"))

```

